# -*- coding: utf-8 -*-
"""ATM-Banking-Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_zdsppYm7Y2Yu5hzcho9IOyf58XHm5h
"""

# -----------------------------
#      ATM MACHINE PROGRAM
#      Clean & Improved Version
# -----------------------------

balance = 1000
PIN = "1234"
MAX_ATTEMPTS = 3


# -----------------------------
#          LOGIN SYSTEM
# -----------------------------
def login():
    attempts = 0
    while attempts < MAX_ATTEMPTS:
        entered = input("Enter your PIN: ")

        if entered == PIN:
            print("✔️ PIN accepted.\n")
            return True

        attempts += 1
        print(f"❌ Incorrect PIN. Attempts left: {MAX_ATTEMPTS - attempts}")

    print("⛔ Too many incorrect attempts. Card blocked.")
    return False


# -----------------------------
#       CHECK BALANCE
# -----------------------------
def check_balance():
    print(f"💰 Your balance is: £{balance}")


# -----------------------------
#           DEPOSIT
# -----------------------------
def deposit():
    global balance
    try:
        amount = float(input("Enter amount to deposit: £"))

        if amount <= 0:
            print("❌ Deposit amount must be positive.")
            return

        balance += amount
        print(f"✔️ £{amount} deposited successfully.")

    except ValueError:
        print("❌ Invalid amount.")


# -----------------------------
#          WITHDRAW
# -----------------------------
def withdraw():
    global balance

    print("\nWithdrawal Menu:")
    print("1 - £10")
    print("2 - £20")
    print("3 - £50")
    print("4 - Other amount")

    choice = input("Choose an option: ")

    if choice == '1':
        amount = 10
    elif choice == '2':
        amount = 20
    elif choice == '3':
        amount = 50
    elif choice == '4':
        try:
            amount = int(input("Enter amount (must be multiple of £10): £"))
            if amount <= 0:
                print("❌ Amount must be positive.")
                return
            if amount % 10 != 0:
                print("❌ Amount must be a multiple of £10.")
                return
        except ValueError:
            print("❌ Invalid amount.")
            return
    else:
        print("❌ Invalid choice.")
        return

    # Check funds
    if amount > balance:
        print("❌ Insufficient funds.")
        return

    # Perform withdrawal
    balance -= amount
    print(f"✔️ £{amount} withdrawn successfully.")


# -----------------------------
#          MAIN MENU
# -----------------------------
def main_menu():
    while True:
        print("\n----- ATM MENU -----")
        print("1 - Check Balance")
        print("2 - Deposit Money")
        print("3 - Withdraw Money")
        print("4 - Exit")

        option = input("Choose an option: ")

        if option == '1':
            check_balance()
        elif option == '2':
            deposit()
        elif option == '3':
            withdraw()
        elif option == '4':
            print("👋 Thank you for using the ATM. Goodbye!")
            break
        else:
            print("❌ Invalid option. Please try again.")


# -----------------------------
#        PROGRAM START
# -----------------------------
if login():
    main_menu()